name: prospectius
description: "A Flutter application for Prospectius."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mysql1: ^0.20.0
  provider: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  uuid: ^4.0.0
  csv: ^6.0.0
  file_picker: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_linter:
    sdk: flutter

flutter:
  uses-material-design: true
